uses: fx31337/mql-tester-action@master
with:
    BtDeposit: 100000
    BtDest: ${{ github.workspace }}/_results
    BtMonths: ${{ matrix.month }}
    BtYears: ${{ matrix.year }}
    OptFormatBrief: true
    OptFormatJson: true
    OptVerbose: true
    TestExpert: "Water"
    TestPeriod: H1
    TestReportName: Report-${{ matrix.year }}-${{ matrix.month }}

