name: Backtest

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - "master"
      - "dev*"
    paths-ignore:
      - "*.md"
  push:
    branches:
      - "master"
      - "dev*"
    paths-ignore:
      - "*.md"

jobs:
  Compile:
    defaults:
      run:
        shell: powershell
    runs-on: windows-latest
    steps:
      - name: Compile for MQL4
        uses: fx31337/mql-compile-action@master
        with:
          include: .
          init-platform: true
          mt-version: 5.0.0.2361
          path: Water.mq4
          verbose: true
      - name: List compiled files
        run: "(Get-ChildItem -Recurse -Path . -Include *.ex[45]).fullname"
      - run: Get-Location
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Water
          path: Water.ex4"
  Test:
    needs: Compile
    runs-on: ubuntu-latest
    strategy:
      matrix:
        month: [1]
        year: [2018, 2019]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: Water
      - name: Run strategy
        uses: ea31337/mql-tester-action@dev
        with:
          BtDeposit: 100000
          BtDest: ${{ github.workspace }}/_results
          BtMonths: ${{ matrix.month }}
          BtYears: ${{ matrix.year }}
          OptFormatBrief: true
          OptFormatJson: true
          OptVerbose: true
          TestExpert: "Water"
          TestPeriod: H1
          TestReportName: Report-${{ matrix.year }}-${{ matrix.month }}
      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: ${{ github.workspace }}/_results/*.*
