name: telegram message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: -1001192825873
          token: 1639132129:AAFzPAP-fRvpoyoQ2NrgsWm9GuTpIRnwO1s
          format: markdown
          args: ${{ github.repo }} We have a ${{ github.github.event.name }} event. Kösz ${{ github.actor }} | ${{ github.event.path }}
