name: telegram message
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send custom message with args
        uses: appleboy/telegram-action@master
        with:
          to: -1001192825873
          token: 1639132129:AAFzPAP-fRvpoyoQ2NrgsWm9GuTpIRnwO1s
          formt: markdown
          message: ```${{ github.repository }}
          We have a ${{ github.github.event_name }} event. 
          Kösz ${{ github.actor }}```
